### ISSUE TITLE
fastx_converter --help

### ISSUE THREAD

**Issue by sguida** [ncgr/seqtools2#2]
fastx_converter help currently reads

 _--output_quality INTEGER  Quality to assign if converting from fastq to
                             fasta (default:40)_

Should this be "from fasta to fastq?"  I also just can't get this to run, but that could be user error.  Or possibly related to an expectation for a quality flag?

**Comment by ctcncgr** [comment]
Thanks for the bug report.

This is now fixed.  It was definitely not user error :).  There was a point where I guess I changed the input argument for click and didn't translate it to passing the value to the actual method with the correct variable name.
